Numpy is a powerfull tool for numerical calculations. Its main strength is an efficient work with arrays. The key class is `ndarray`. Many scientific libraries build on numpy.

In [ ]:
import numpy as np
a = np.array([1, 2, 3])

Arrays can be used as mathematical function or operators arguments, performing element-wise operations:

In [ ]:
a_squared = a ** 2
print(a_squared)
print(np.sqrt(a))

[1 4 9]
[1.         1.41421356 1.73205081]


Arrays can be multiplied by other arrays. Element-by-element operations are performed.

In [ ]:
a_cubed = a * a_squared
print(a_cubed)

[ 1  8 27]


Arrays can also be multiplied by a scalar value or scalar values can be added to arrays.

In [ ]:
print(a * 7)
print(a + 7)


[ 7 14 21]
[ 8  9 10]


The number of elements in a 1D array is called the shape of the array. More generally, the array shape describes the number of elements in each dimension. The ability to stretch or replicate an array along specific dimenstions is called broadcasting. In the above example, the scalar multiplier was broadcasted to an array of shape (3,).

In [ ]:
print(a.shape)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.shape)

(3,)
(2, 3)


Numpy supports linear algebra calculations. E.g. the dot product evaluation.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
print(np.dot(a, b))

14


Or matrix multiplication:

In [ ]:
M = np.array([[1, 2, 3], [1, 2, 3]])
print(np.dot(M, a))

[14 14]


An example how to solve a system of linear equations:

In [ ]:
# prompt: An example how to solve a system of linear equations using numpy.

import numpy as np

# Example system of equations:
# 2x + 3y = 8
# x - y = -1

# Coefficient matrix
A = np.array([[2, 3], [1, -1]])

# Constant vector
b = np.array([8, -1])

# Solve for x and y
x = np.linalg.solve(A, b)

# Print the solution
print("Solution:")
print("x =", x[0])
print("y =", x[1])


Solution:
x = 1.0
y = 2.0
